### ISSUE TITLE
tsc: command not found

### ISSUE THREAD

**Issue by nzjony** [vladkrutenyuk/threejs-world-map-interactive#2]
I tried to run locally but get:

npm run dev

> three.js-typescript-tutorial@1.0.0 dev /Users/jonstich/dev/threejs-world-map-interactive
> concurrently -k "tsc -p ./src/server -w" "tsc -p ./src/client -w" "nodemon ./dist/server/server.js"

[0] /bin/sh: tsc: command not found

I think it needs to be part of the package.json.

I added it locally, but then I get different errors.

**Comment by vladkrutenyuk** [comment]
you need to compile it first time and after that use `npm run dev`
1) compile server:
`tsc -p ./src/server`
2) compile client:
`tsc -p ./src/client`
3) after that u can use command
`npm run dev`

lmk if it works or not :)

**Comment by nzjony** [comment]
@vladkrutenyuk , 

When I try: `tsc -p ./src/server`, I get: 
`fish: Unknown command tsc`

I.e. I don't have it installed globally.

Though I tried using `npx`, i.e. `npx tsc -p ./src/server` and the second issue I get is:

```
error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
error TS5023: Unknown compiler option 'esModuleInterop'.
```

**Comment by vladkrutenyuk** [comment]
yo, try again
some fixes was added

**Comment by nzjony** [comment]
@vladkrutenyuk , which branch should I be on? Master?

I switched to `develop` and get the following issue:

```
npm run dev

> three.js-typescript-tutorial@1.0.0 dev /Users/jonstich/dev/threejs-world-map-interactive
> concurrently -k "npm run build-server" "npm run build-client" "npm run watch-server"

[1] 
[1] > three.js-typescript-tutorial@1.0.0 build-client /Users/jonstich/dev/threejs-world-map-interactive
[1] > tsc -p ./src/client -w
[1] 
[0] 
[0] > three.js-typescript-tutorial@1.0.0 build-server /Users/jonstich/dev/threejs-world-map-interactive
[0] > tsc -p ./src/server -w
[0] 
[2] 
[2] > three.js-typescript-tutorial@1.0.0 watch-server /Users/jonstich/dev/threejs-world-map-interactive
[2] > nodemon ./dist/server/server.js
[2] 
[2]   Usage: nodemon [nodemon options] [script.js] [args]
[2] 
[2]   See "nodemon --help" for more.
[2] 
[2] npm run watch-server exited with code 0
--> Sending SIGTERM to other processes..
[0] npm run build-server exited with code SIGTERM
--> Sending SIGTERM to other processes..
[1] npm run build-client exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! three.js-typescript-tutorial@1.0.0 dev: `concurrently -k "npm run build-server" "npm run build-client" "npm run watch-server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three.js-typescript-tutorial@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonstich/.npm/_logs/2020-11-04T07_48_33_112Z-debug.log
```

Seems there is an issue using `nodemon` ?

**Comment by vladkrutenyuk** [comment]
yo, I have updated project
track to dev branch and...

- `yarn install`
- `yarn watch`
- open in browser as `http://localhost:1234/`

p.s. of course Node.js should be installed before

**Comment by nzjony** [comment]
thanks @vladkrutenyuk , it works!
